import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ['400', '900'],
  subsets: ['latin'],
});
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
